export type CharactersStatByFaction = {
  collection: 'characters_stat_by_faction';
  format: {
    character_id: string;
    stat_name: string;
    profile_id: string;
    value_forever_vs: string;
    value_forever_nc: string;
    value_forever_tr: string;
    value_monthly_vs: string;
    value_monthly_nc: string;
    value_monthly_tr: string;
    value_weekly_vs: string;
    value_weekly_nc: string;
    value_weekly_tr: string;
    value_daily_vs: string;
    value_daily_nc: string;
    value_daily_tr: string;
    value_one_life_max_vs: string;
    value_one_life_max_nc: string;
    value_one_life_max_tr: string;
    last_save: string;
    last_save_date: string;
  };
  paths:
    | 'character_id'
    | 'stat_name'
    | 'profile_id'
    | 'value_forever_vs'
    | 'value_forever_nc'
    | 'value_forever_tr'
    | 'value_monthly_vs'
    | 'value_monthly_nc'
    | 'value_monthly_tr'
    | 'value_weekly_vs'
    | 'value_weekly_nc'
    | 'value_weekly_tr'
    | 'value_daily_vs'
    | 'value_daily_nc'
    | 'value_daily_tr'
    | 'value_one_life_max_vs'
    | 'value_one_life_max_nc'
    | 'value_one_life_max_tr'
    | 'last_save'
    | 'last_save_date';
  partialPaths:
    | 'character_id'
    | 'stat_name'
    | 'profile_id'
    | 'value_forever_vs'
    | 'value_forever_nc'
    | 'value_forever_tr'
    | 'value_monthly_vs'
    | 'value_monthly_nc'
    | 'value_monthly_tr'
    | 'value_weekly_vs'
    | 'value_weekly_nc'
    | 'value_weekly_tr'
    | 'value_daily_vs'
    | 'value_daily_nc'
    | 'value_daily_tr'
    | 'value_one_life_max_vs'
    | 'value_one_life_max_nc'
    | 'value_one_life_max_tr'
    | 'last_save'
    | 'last_save_date';
  conditions: {
    character_id?: string;
    last_save?: string;
    last_save_date?: string;
    profile_id?: string;
    stat_name?: string;
    value_daily_nc?: string;
    value_daily_tr?: string;
    value_daily_vs?: string;
    value_forever_nc?: string;
    value_forever_tr?: string;
    value_forever_vs?: string;
    value_monthly_nc?: string;
    value_monthly_tr?: string;
    value_monthly_vs?: string;
    value_one_life_max_nc?: string;
    value_one_life_max_tr?: string;
    value_one_life_max_vs?: string;
    value_weekly_nc?: string;
    value_weekly_tr?: string;
    value_weekly_vs?: string;
  };
};
