export type Effect = {
  collection: 'effect';
  format: {
    effect_id: string;
    effect_type_id: string;
    ability_id: string;
    target_type_id: string;
    resist_type_id: string;
    is_drain: string;
    duration_seconds: string;
    param1: string;
    param2: string;
    param3: string;
    param4: string;
    param5: string;
    param6: string;
    param7: string;
    param8: string;
    param9: string;
    param10: string;
    param11: string;
    param12: string;
    param13: string;
  };
  paths:
    | 'effect_id'
    | 'effect_type_id'
    | 'ability_id'
    | 'target_type_id'
    | 'resist_type_id'
    | 'is_drain'
    | 'duration_seconds'
    | 'param1'
    | 'param2'
    | 'param3'
    | 'param4'
    | 'param5'
    | 'param6'
    | 'param7'
    | 'param8'
    | 'param9'
    | 'param10'
    | 'param11'
    | 'param12'
    | 'param13';
  partialPaths:
    | 'effect_id'
    | 'effect_type_id'
    | 'ability_id'
    | 'target_type_id'
    | 'resist_type_id'
    | 'is_drain'
    | 'duration_seconds'
    | 'param1'
    | 'param2'
    | 'param3'
    | 'param4'
    | 'param5'
    | 'param6'
    | 'param7'
    | 'param8'
    | 'param9'
    | 'param10'
    | 'param11'
    | 'param12'
    | 'param13';
  conditions: {
    ability_id?: string;
    duration_seconds?: string;
    effect_id?: string;
    effect_type_id?: string;
    is_drain?: string;
    param1?: string;
    param10?: string;
    param11?: string;
    param12?: string;
    param13?: string;
    param2?: string;
    param3?: string;
    param4?: string;
    param5?: string;
    param6?: string;
    param7?: string;
    param8?: string;
    param9?: string;
    resist_type_id?: string;
    target_type_id?: string;
  };
};
