export type EmpireScores = {
  collection: 'empire_scores';
  format: {
    tracker_name: string;
    tracker_description: string;
    start_date: string;
    start_time: string;
    end_date: string;
    end_time: string;
    name: {
      de: string;
      en: string;
      es: string;
      fr: string;
      it: string;
      tr: string;
    };
    description: {
      de: string;
      en: string;
      es: string;
      fr: string;
      it: string;
      tr: string;
    };
  };
  paths:
    | 'tracker_name'
    | 'tracker_description'
    | 'start_date'
    | 'start_time'
    | 'end_date'
    | 'end_time'
    | 'name.de'
    | 'name.en'
    | 'name.es'
    | 'name.fr'
    | 'name.it'
    | 'name.tr'
    | 'description.de'
    | 'description.en'
    | 'description.es'
    | 'description.fr'
    | 'description.it'
    | 'description.tr';
  partialPaths:
    | 'tracker_name'
    | 'tracker_description'
    | 'start_date'
    | 'start_time'
    | 'end_date'
    | 'end_time'
    | 'name'
    | 'name.de'
    | 'name.en'
    | 'name.es'
    | 'name.fr'
    | 'name.it'
    | 'name.tr'
    | 'description'
    | 'description.de'
    | 'description.en'
    | 'description.es'
    | 'description.fr'
    | 'description.it'
    | 'description.tr';
  conditions: {
    description?: string;
    'description.de'?: string;
    'description.en'?: string;
    'description.es'?: string;
    'description.fr'?: string;
    'description.it'?: string;
    'description.tr'?: string;
    end_date?: string;
    end_time?: string;
    name?: string;
    'name.de'?: string;
    'name.en'?: string;
    'name.es'?: string;
    'name.fr'?: string;
    'name.it'?: string;
    'name.tr'?: string;
    start_date?: string;
    start_time?: string;
    tracker_description?: string;
    tracker_name?: string;
  };
};
