export type FireMode = {
  collection: 'fire_mode';
  format: {
    fire_mode_id: string;
    item_id: string;
    type: string;
    description: {
      de: string;
      en: string;
      es: string;
      fr: string;
      it: string;
      tr: string;
    };
    player_state_group_id: string;
    cof_recoil: string;
    reload_time_ms: string;
    reload_chamber_time_ms: string;
    pellets_per_shot: string;
    pellet_spread: string;
    default_zoom: string;
    muzzle_velocity: string;
    speed: string;
    max_speed: string;
    damage_radius: string;
    projectile_description: string;
    damage_type: string;
    damage: string;
    damage_min: string;
    damage_max: string;
    damage_min_range: string;
    damage_max_range: string;
    damage_target_type: string;
    damage_resist_type: string;
    indirect_damage_max: string;
    indirect_damage_max_range: string;
    indirect_damage_min: string;
    indirect_damage_min_range: string;
    indirect_damage_target_type: string;
    indirect_damage_resist_type: string;
  };
  paths:
    | 'fire_mode_id'
    | 'item_id'
    | 'type'
    | 'description.de'
    | 'description.en'
    | 'description.es'
    | 'description.fr'
    | 'description.it'
    | 'description.tr'
    | 'player_state_group_id'
    | 'cof_recoil'
    | 'reload_time_ms'
    | 'reload_chamber_time_ms'
    | 'pellets_per_shot'
    | 'pellet_spread'
    | 'default_zoom'
    | 'muzzle_velocity'
    | 'speed'
    | 'max_speed'
    | 'damage_radius'
    | 'projectile_description'
    | 'damage_type'
    | 'damage'
    | 'damage_min'
    | 'damage_max'
    | 'damage_min_range'
    | 'damage_max_range'
    | 'damage_target_type'
    | 'damage_resist_type'
    | 'indirect_damage_max'
    | 'indirect_damage_max_range'
    | 'indirect_damage_min'
    | 'indirect_damage_min_range'
    | 'indirect_damage_target_type'
    | 'indirect_damage_resist_type';
  partialPaths:
    | 'fire_mode_id'
    | 'item_id'
    | 'type'
    | 'description'
    | 'description.de'
    | 'description.en'
    | 'description.es'
    | 'description.fr'
    | 'description.it'
    | 'description.tr'
    | 'player_state_group_id'
    | 'cof_recoil'
    | 'reload_time_ms'
    | 'reload_chamber_time_ms'
    | 'pellets_per_shot'
    | 'pellet_spread'
    | 'default_zoom'
    | 'muzzle_velocity'
    | 'speed'
    | 'max_speed'
    | 'damage_radius'
    | 'projectile_description'
    | 'damage_type'
    | 'damage'
    | 'damage_min'
    | 'damage_max'
    | 'damage_min_range'
    | 'damage_max_range'
    | 'damage_target_type'
    | 'damage_resist_type'
    | 'indirect_damage_max'
    | 'indirect_damage_max_range'
    | 'indirect_damage_min'
    | 'indirect_damage_min_range'
    | 'indirect_damage_target_type'
    | 'indirect_damage_resist_type';
  conditions: {
    cof_recoil?: string;
    damage?: string;
    damage_max?: string;
    damage_max_range?: string;
    damage_min?: string;
    damage_min_range?: string;
    damage_radius?: string;
    damage_resist_type?: string;
    damage_target_type?: string;
    damage_type?: string;
    default_zoom?: string;
    description?: string;
    'description.de'?: string;
    'description.en'?: string;
    'description.es'?: string;
    'description.fr'?: string;
    'description.it'?: string;
    'description.tr'?: string;
    fire_mode_id?: string;
    indirect_damage_max?: string;
    indirect_damage_max_range?: string;
    indirect_damage_min?: string;
    indirect_damage_min_range?: string;
    indirect_damage_resist_type?: string;
    indirect_damage_target_type?: string;
    item_id?: string;
    max_speed?: string;
    muzzle_velocity?: string;
    pellet_spread?: string;
    pellets_per_shot?: string;
    player_state_group_id?: string;
    projectile_description?: string;
    reload_chamber_time_ms?: string;
    reload_time_ms?: string;
    speed?: string;
    type?: string;
  };
};
