export type Item = {
  collection: 'item';
  format: {
    item_id: string;
    item_type_id: string;
    item_category_id: string;
    activatable_ability_id: string;
    passive_ability_id: string;
    is_vehicle_weapon: string;
    name: {
      de: string;
      en: string;
      es: string;
      fr: string;
      it: string;
      tr: string;
    };
    description: {
      de: string;
      en: string;
      es: string;
      fr: string;
      it: string;
      tr: string;
    };
    faction_id: string;
    max_stack_size: string;
    image_set_id: string;
    image_id: string;
    image_path: string;
    skill_set_id: string;
    is_default_attachment: string;
  };
  paths:
    | 'item_id'
    | 'item_type_id'
    | 'item_category_id'
    | 'activatable_ability_id'
    | 'passive_ability_id'
    | 'is_vehicle_weapon'
    | 'name.de'
    | 'name.en'
    | 'name.es'
    | 'name.fr'
    | 'name.it'
    | 'name.tr'
    | 'description.de'
    | 'description.en'
    | 'description.es'
    | 'description.fr'
    | 'description.it'
    | 'description.tr'
    | 'faction_id'
    | 'max_stack_size'
    | 'image_set_id'
    | 'image_id'
    | 'image_path'
    | 'skill_set_id'
    | 'is_default_attachment';
  partialPaths:
    | 'item_id'
    | 'item_type_id'
    | 'item_category_id'
    | 'activatable_ability_id'
    | 'passive_ability_id'
    | 'is_vehicle_weapon'
    | 'name'
    | 'name.de'
    | 'name.en'
    | 'name.es'
    | 'name.fr'
    | 'name.it'
    | 'name.tr'
    | 'description'
    | 'description.de'
    | 'description.en'
    | 'description.es'
    | 'description.fr'
    | 'description.it'
    | 'description.tr'
    | 'faction_id'
    | 'max_stack_size'
    | 'image_set_id'
    | 'image_id'
    | 'image_path'
    | 'skill_set_id'
    | 'is_default_attachment';
  conditions: {
    activatable_ability_id?: string;
    description?: string;
    'description.de'?: string;
    'description.en'?: string;
    'description.es'?: string;
    'description.fr'?: string;
    'description.it'?: string;
    'description.tr'?: string;
    faction_id?: string;
    image_id?: string;
    image_path?: string;
    image_set_id?: string;
    is_default_attachment?: string;
    is_vehicle_weapon?: string;
    item_category_id?: string;
    item_id?: string;
    item_type_id?: string;
    max_stack_size?: string;
    name?: string;
    'name.de'?: string;
    'name.en'?: string;
    'name.es'?: string;
    'name.fr'?: string;
    'name.it'?: string;
    'name.tr'?: string;
    passive_ability_id?: string;
    release_time?: string;
    skill_set_id?: string;
  };
};
