export type WeaponDatasheet = {
  collection: 'weapon_datasheet';
  format: {
    item_id: string;
    damage: string;
    damage_min: string;
    damage_max: string;
    direct_damage: string;
    indirect_damage: string;
    fire_cone: string;
    fire_cone_min: string;
    fire_cone_max: string;
    fire_rate_ms: string;
    fire_rate_ms_min: string;
    fire_rate_mx_max: string;
    reload_ms: string;
    reload_ms_min: string;
    reload_ms_max: string;
    clip_size: string;
    capacity: string;
    range: {
      de: string;
      en: string;
      es: string;
      fr: string;
      it: string;
      tr: string;
    };
    show_clip_size: string;
    show_fire_modes: string;
    show_range: string;
  };
  paths:
    | 'item_id'
    | 'damage'
    | 'damage_min'
    | 'damage_max'
    | 'direct_damage'
    | 'indirect_damage'
    | 'fire_cone'
    | 'fire_cone_min'
    | 'fire_cone_max'
    | 'fire_rate_ms'
    | 'fire_rate_ms_min'
    | 'fire_rate_mx_max'
    | 'reload_ms'
    | 'reload_ms_min'
    | 'reload_ms_max'
    | 'clip_size'
    | 'capacity'
    | 'range.de'
    | 'range.en'
    | 'range.es'
    | 'range.fr'
    | 'range.it'
    | 'range.tr'
    | 'show_clip_size'
    | 'show_fire_modes'
    | 'show_range';
  partialPaths:
    | 'item_id'
    | 'damage'
    | 'damage_min'
    | 'damage_max'
    | 'direct_damage'
    | 'indirect_damage'
    | 'fire_cone'
    | 'fire_cone_min'
    | 'fire_cone_max'
    | 'fire_rate_ms'
    | 'fire_rate_ms_min'
    | 'fire_rate_mx_max'
    | 'reload_ms'
    | 'reload_ms_min'
    | 'reload_ms_max'
    | 'clip_size'
    | 'capacity'
    | 'range'
    | 'range.de'
    | 'range.en'
    | 'range.es'
    | 'range.fr'
    | 'range.it'
    | 'range.tr'
    | 'show_clip_size'
    | 'show_fire_modes'
    | 'show_range';
  conditions: {
    capacity?: string;
    clip_size?: string;
    damage?: string;
    damage_max?: string;
    damage_min?: string;
    direct_damage?: string;
    fire_cone?: string;
    fire_cone_max?: string;
    fire_cone_min?: string;
    fire_rate_ms?: string;
    fire_rate_ms_min?: string;
    fire_rate_mx_max?: string;
    indirect_damage?: string;
    item_id?: string;
    range?: string;
    'range.de'?: string;
    'range.en'?: string;
    'range.es'?: string;
    'range.fr'?: string;
    'range.it'?: string;
    'range.tr'?: string;
    reload_ms?: string;
    reload_ms_max?: string;
    reload_ms_min?: string;
    show_clip_size?: string;
    show_fire_modes?: string;
    show_range?: string;
  };
};
