export type ZoneEffect = {
  collection: 'zone_effect';
  format: {
    zone_effect_id: string;
    zone_effect_type_id: string;
    ability_id: string;
    param1: string;
    param2: string;
    param3: string;
    param4: string;
    param5: string;
    param6: string;
    param7: string;
    param8: string;
    param9: string;
    param10: string;
    param11: string;
    param12: string;
    param13: string;
    param14: string;
    string1: string;
    string2: string;
    string3: string;
    string4: string;
  };
  paths:
    | 'zone_effect_id'
    | 'zone_effect_type_id'
    | 'ability_id'
    | 'param1'
    | 'param2'
    | 'param3'
    | 'param4'
    | 'param5'
    | 'param6'
    | 'param7'
    | 'param8'
    | 'param9'
    | 'param10'
    | 'param11'
    | 'param12'
    | 'param13'
    | 'param14'
    | 'string1'
    | 'string2'
    | 'string3'
    | 'string4';
  partialPaths:
    | 'zone_effect_id'
    | 'zone_effect_type_id'
    | 'ability_id'
    | 'param1'
    | 'param2'
    | 'param3'
    | 'param4'
    | 'param5'
    | 'param6'
    | 'param7'
    | 'param8'
    | 'param9'
    | 'param10'
    | 'param11'
    | 'param12'
    | 'param13'
    | 'param14'
    | 'string1'
    | 'string2'
    | 'string3'
    | 'string4';
  conditions: {
    ability_id?: string;
    param1?: string;
    param2?: string;
    param3?: string;
    param4?: string;
    param5?: string;
    param6?: string;
    param7?: string;
    param8?: string;
    param9?: string;
    param10?: string;
    param11?: string;
    param12?: string;
    param13?: string;
    param14?: string;
    string1?: string;
    string2?: string;
    string3?: string;
    string4?: string;
    zone_effect_id?: string;
    zone_effect_type_id?: string;
  };
};
