export enum State {
  IDLE,
  CONNECTING,
  NEARLY,
  RECONNECTING,
  READY,
  DISCONNECTED,
}

export enum Events {
  STREAM_READY = 'ready',
  STREAM_DISCONNECTED = 'disconnected',
  STREAM_RECONNECTING = 'reconnecting',
  STREAM_DESTROYED = 'destroyed',
  STREAM_CLOSE = 'close',
  ERROR = 'error',
  WARN = 'warn',
  DEBUG = 'debug',
  PS2_EVENT = 'ps2Event',
  PS2_DUPLICATE = 'duplicate',
  PS2_SUBSCRIBED = 'subscribed',
  PS2_SERVICE_STATE = 'serviceState',
  PS2_ACHIEVEMENT = 'achievementEarned',
  PS2_RANK_UP = 'battleRankUp',
  PS2_DEATH = 'death',
  PS2_EXPERIENCE = 'gainExperience',
  PS2_ITEM = 'itemAdded',
  PS2_CAPTURE = 'playerFacilityCapture',
  PS2_DEFEND = 'playerFacilityDefend',
  PS2_LOGIN = 'playerLogin',
  PS2_LOGOUT = 'playerLogout',
  PS2_SKILL = 'skillAdded',
  PS2_VEHICLE_DESTROYED = 'vehicleDestroy',
  PS2_LOCK = 'continentLock',
  PS2_UNLOCK = 'continentUnlock',
  PS2_CONTROL = 'facilityControl',
  PS2_META_EVENT = 'metagameEvent',
}
