export default effect;

type effect = {
    effect_id: string,
    effect_type_id: string,
    ability_id: string,
    target_type_id: string,
    resist_type_id: string,
    is_drain: string,
    duration_seconds: string,
    param1: string,
    param2: string,
    param3: string,
    param4: string,
    param5: string,
    param6: string,
    param7: string,
    param8: string,
    param9: string,
    param10: string,
    param11: string,
    param12: string,
    param13: string,
    [prop: string]: any,
};
