export type outfitMemberExtended = {
    character_id: string,
    member_since: string,
    member_since_date: string,
    member_rank: string,
    member_rank_ordinal: string,
    outfit_id: string,
    name: string,
    name_lower: string,
    alias: string,
    alias_lower: string,
    time_created: string,
    time_created_date: string,
    leader_character_id: string,
    member_count: string,
    [prop: string]: any,
};
