export type projectile = {
    projectile_id: string,
    projectile_flight_type_id: string,
    speed: string,
    speed_max: string,
    acceleration: string,
    turn_rate: string,
    lifespan: string,
    drag: string,
    gravity: string,
    lockon_acceleration: string,
    lockon_lifespan: string,
    arm_distance: string,
    tether_distance: string,
    detonate_distance: string,
    detonate_on_contact: string,
    sticky: string,
    sticks_to_players: string,
    lockon_lose_angle: string,
    lockon_seek_in_flight: string
    [prop: string]: any,
};
