name: CI

on:
  push:
    branches:
      - master

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    if: github.repository == 'microwavekonijn/ps2census'
    runs-on: ubuntu-latest
    environment:
      name: release
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 22.x
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Create PR or publish
        uses: changesets/action@v1
        with:
          publish: yarn changeset publish
          commit: 'chore: release'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
