name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  compile-test:
    name: Compile Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: pnpm/action-setup@v6
      - uses: actions/setup-node@v7
        with:
          node-version: 24
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install --frozen-lockfile --silent
      - name: Compile
        run: pnpm build

  test:
    name: Integration Test
    runs-on: ubuntu-latest
    environment:
      name: test
    steps:
      - uses: actions/checkout@v7
      - uses: pnpm/action-setup@v6
      - uses: actions/setup-node@v7
        with:
          node-version: 24
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install --frozen-lockfile --silent
      - name: Run
        run: pnpm test
        env:
          SERVICE_ID: ${{ secrets.SERVICE_ID }}
          TIMEOUT: 15
